### ISSUE TITLE
zfssnap reports trying to delete pools

### ISSUE THREAD

**Issue by mlindgren80** [zfsnap/zfsnap#67]
Here is the output that gets mailed to me:
```
Scrubbing of zfs pools:
   starting scrub of pool 'ssdmirror':
      consult 'zpool status ssdmirror' for the result
   starting scrub of pool 'usbenc':
      consult 'zpool status usbenc' for the result
   skipping scrubbing of pool 'zfsbak':
      last scrubbing is 29 days ago, threshold is set to 30 days
   skipping scrubbing of pool 'zfsraid2':
      last scrubbing is 29 days ago, threshold is set to 30 days
   starting scrub of pool 'zroot':
      consult 'zpool status zroot' for the result
FATAL: trying to delete zfs pool or filesystem? WTF?
  This is bug, we definitely don't want that.
  Please report it to https://github.com/graudeejs/zfSnap/issues
  Don't panic, nothing was deleted :)
```
And here is my config:
```sh
daily_zfsnap_enable="YES"

daily_zfsnap_delete_enable="YES"

daily_zfsnap_fs="zfsraid2/shows zfsbak/movies"
daily_zfsnap_flags="-s -S"
daily_zfsnap_verbose="YES"
daily_zfsnap_delete_flags="-s -S"
daily_zfsnap_delete_verbose="YES"


daily_scrub_zfs_enable="YES"
daily_scrub_zfs_zroot_threshold="7"
daily_scrub_zfs_ssdmirror_threshold="7"
daily_scrub_zfs_zfsbak_threshold="30"
daily_scrub_zfs_usbenc_threshold="14"
daily_scrub_zfs_zfsraid2_threshold="30"
```

As stated in the email output, it told me to report the issue, so here I am :)  I am running FreeBSD 10.1 with its associated ZFS version.

**Comment by kim0** [comment]
hi, I'm hitting this bug too, and it's not clear why. It's a scary error message, so can someone explain more what's happening .. Thanks!

**Comment by graudeejs** [comment]
Execute this and post output:
```sh
 zfSnap -zpool28fix -n -d -p 'hourly-' -p 'daily-' -p 'weekly-' -p 'monthly-' -p 'reboot-'
```

And then execute this and post output
```sh
sh -x /usr/local/sbin/zfSnap -zpool28fix -n -d -p 'hourly-' -p 'daily-' -p 'weekly-' -p 'monthly-' -p 'reboot-'
```

Note: I think you're missing -zpool28fix flag in **daily_zfsnap_delete_flags**. Not that it should cause this misbehavior, but still.

**Comment by kim0** [comment]
@graudeejs .. The first command returns nothing .. The second one returns http://fpaste.org/250760/

Thanks for helping!

**Comment by graudeejs** [comment]
Weird, 1st command should return list of zfs commands
Something like:
```
$ zfSnap -zpool28fix -v -n -d -p 'hourly-' -p 'daily-' -p 'weekly-' -p 'monthly-' -p 'reboot-'          
/sbin/zfs destroy d/FreeBSD/10r1p5_custom@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/FreeBSD/current@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/FreeBSD@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/home/graudeejs/archive@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/home/graudeejs/photo@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/home/graudeejs/videos@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/home/graudeejs@2015-07-28_20.07.12--5d
/sbin/zfs destroy d/home@2015-07-28_20.07.12--5d
```

**Comment by kim0** [comment]
I ran it like 5 times .. nothing at all

**Comment by graudeejs** [comment]
Try latest version from legacy branch, I added few lines in order to see what exactly caused an error.
https://github.com/zfsnap/zfsnap/commit/17b1f389365a57f04448c0800cde327d47baa02e

Try with this one: https://github.com/zfsnap/zfsnap/blob/17b1f389365a57f04448c0800cde327d47baa02e/zfSnap.sh

run:
```sh
./zfSnap.sh -zpool28fix -v -d -p 'hourly-' -p 'daily-' -p 'weekly-' -p 'monthly-' -p 'reboot-'
```
This will try to delete snapshot, and If you get that error, we should see why exactly.

**Comment by graudeejs** [comment]
Btw, @kim0, are you using FreeBSD as well?

**Comment by kim0** [comment]
@graudeejs Yes I'm on freebsd 10.1 ... I'll try that version next

**Comment by graudeejs** [comment]
Any news?

**Comment by scotthesterberg** [comment]
Sorry I replied directly rather than to the mailing list:
I appreciate the input. Gave it a try but there is not enough room for
another full snapshot on my backup store. In addition it will not let me
send another full snap to the same destination i.e. have been backing up to
backup/x if I try to send another full to that same location, even with a
zfs receive  -F.
The snapshots I am sending are ~1.2 TB the only way practical to do regular
backups with out spending an absolute fortune is incremental I am afraid.

I have enabled dedup at the pool level, renamed x to x_old and but that ran
out of space and became very very slow.I was forced to delete the old
backups and pool, make a new one without dedup and start anew.

I have figured out what caused me to have missed snapshot synchronization,
and fixed my cron jobs. I will try and write a check function eventually to
ensure at least one common snapshot is maintained on each system (the
difficulty is that to preserve power/memory/compute the backup system is
powered off most of the day).

Thanks for your help :)

**Comment by graudeejs** [comment]
@scotthesterberg Wrong issue or split personality? I'm confused, since you posted this right after I asked @kim0 a question and your post doesn't seem to fit the issue, or does it? I'm confused

**Comment by scotthesterberg** [comment]
@graudeejs sorry wrong issue.

**Comment by graudeejs** [comment]
Closing for now, since no new input has been provided.
