### ISSUE TITLE
Is this still an active project?

### ISSUE THREAD

**Issue by arronmabrey** [zfsnap/zfsnap#93]
Hello all,

Apologies if the title sounded critical, that's not the intent. I'm just wondering if there are still plans to support this tool going forward. It looks like awhile back there was push for version 2.0.0 and even 2.1.0 with send/recv support but it seems that was never finished.

I'm just now setting up my first zfs deployment with offsite backup (using openzfs on macos) and I'm looking at the current state for tools to manage as much of the automated snapshot and transfer as possible.

I'm just trying to understand where this project is in its lifecycle.

Thanks,
-- Arron

**Comment by aqw** [comment]
Hey @arronmabrey 
No worries about the title. It's a fair question. :-)

I do have a lengthy todo list hanging around for when I get time to sink my teeth into zfsnap again. But, as can be seen, for two years now, I've been hoping that time is "soon."

If you're interested in helping out, I'm happy to review and merge patches. As for when I'll get back into it all, there is a good chance that a project at work in July will force me to spend a week or two on zfsnap. So there is hope indeed. :-)

Out of curiosity, are there any particular features you're in need of?

---Alex

PS, closing this issue as it's not a work item, but we can continue our conversation in here.

**Comment by arronmabrey** [comment]
Wow thanks @aqw for the quick response!

The main issue I'm trying to figure out right now is the transferring portion (e.g. send / recv). 

I have looked at a lot of solutions out there ranging from home-rolled to very comprehensive. I still haven't settled on anything yet. One of the bigest issues for me is portability, because I'm on macOS, everything out there seems to target other operating systems. Which is fair considering macOS is likely not a huge user base from them, it's just a bummer.

The other really nice to have features would be to support:

1. support zfs bookmarks.
2. support send/recv resume.

I'm not sure the status of support for these two features across different zfs flavors. I believe they are supported by all the OpenZFS flavors and maybe more.

**Comment by aqw** [comment]
> The main issue I'm trying to figure out right now is the transferring portion (e.g. send / recv).

So, my plans are to keep send and receive simple, but try to make them smarter. The simple form is just getting the most recent, top-level snapshot of each, and just assume that the origin snapshot exists on both systems. This is very easy to do, and I just need to write it.

Smarter versions would include finding the most recent common snapshot and erroring if one cannot be found. Also having a flag to output the size of the data stream to be sent, so that way the admin can script decisions based off of how much data is being sent. One night, I had a... less than careful user generate 4 TiB in a non-scratch folder. I was less than amused and I had no scripts to warn me as everything got sent to the backup server. :-/

> One of the bigest issues for me is portability, because I'm on macOS, everything out there seems to target other operating systems. Which is fair considering macOS is likely not a huge user base from them, it's just a bummer.

The core feature of zfsnap is portability. If it doesn't run on OS X 1) I'll be very surprised, and 2) it's a bug and I'll fix it right away. Our goal is to run on /every/ system ZFS can run on. Historical and otherwise.

> The other really nice to have features would be to support:
> 
>     support zfs bookmarks.

So, I would love bookmarks as well, but unfortunately (from what I understand) they don't work as nicely as they should. The key missing feature is that they aren't recursive. They're only for one level. If I'm missing something, I would /love/ to be corrected, because they would be a very useful feature.

>     support send/recv resume.

How do you see zfsnap supporting resumable send? I've never used it, but I envision zfsnap providing tools which make it easier to work with zfs send and receive, rather than acting as a replacement or something which sits over them and calls them for you. IMO, it's too complicated to anticipate all the possible deployments. Better to give admins to tools to make it easy and let them write the 3-liner script they need for their situation.

> I'm not sure the status of support for these two features across different zfs flavors. I believe they are supported by all the OpenZFS flavors and maybe more.

Everything (except for Oracle's weird version) should now support bookmarks and resumable send/recv. I don't know about the OS X guys, but FreeBSD, ZoL, and the IllumOS guys are doing a really good job reducing the deltas and getting everyone back on the same page. They've put a lot of work into it and it's beginning to show.

---Alex
